# Generated by Django 4.2.3 on 2023-08-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
