# Generated by Django 4.2.3 on 2023-08-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='phone',
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_no',
            field=models.CharField(default='', max_length=50),
        ),
    ]
